// import type { Metadata } from "next";
// import localFont from "next/font/local";
// import "./globals.css";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }


// import React from 'react';
// import './globals.css';

// export const metadata = {
//   title: 'Syslab.ai - AI Solutions',
//   description: 'asasSyslab.ai provides cutting-edge AI solutions, web interfaces, and cross-platform mobile apps.',
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en">

//       {/* <head>
//         <link rel="icon" type="image/png" href="/logo.png" />
//       </head> */}
//       <body>{children}</body>
//     </html>
//   );
// }


import React from 'react';
import './globals.css';

export const metadata = {
  title: 'Syslab.ai - AI Solutions',
  description: 'Syslab.ai provides cutting-edge AI solutions, web interfaces, and cross-platform mobile apps.',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        {/* svg to png then logo.png to favicon.ico and then use line <link rel="icon" href="/favicon.ico" sizes="4x4"/> */}
        <link rel="icon" href="favicon.svg"/>
        {/* <link rel="icon" type="image/png" sizes="4x4" href="/logo.png" /> */}


        {/* Global Meta Tags */}
        <meta name="keywords" content="AI Solutions, Web Interfaces, Mobile Apps, Syslab.ai" />
        <meta name="author" content="Syslab.ai" />
        <meta property="og:type" content="website" />
        <meta property="og:site_name" content="syslab-ai" />
      </head>
      <body>{children}</body>
    </html>
  );
}
